:q
# 
# Copyright (C) 2009 Claudio Mignanti
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=meta-acmeconf
PKG_VERSION:=1
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/meta-acmeconf
  SECTION:=utils
  CATEGORY:=Acme
  TITLE:=Default Acme configuration
  MAINTAINER:=Claudio Mignanti <mignanti@acmesystems.it>
  #utils
  DEPENDS:=+fdisk +e2fsprogs +strace +nano +minicom +setserial +tcpdump
  #interface
  DEPENDS+=+webif +webif-applications 
  #lang
  DEPENDS+=+lighttpd +lighttpd-mod-fastcgi +php5 +php5-fastcgi
  #kernel
  DEPENDS+=+kmod-usb-ohci
  DEFAULT:=y
endef

define Package/meta-acmeconf/description
   Meta packages that define Acme configuration
endef

define Build/Compile
endef


define Package/meta-acmeconf/install
	$(INSTALL_DIR) $(1)/
	$(CP) -r ./files/* $(1)/
	$(INSTALL_DIR) -p $(1)/web
endef

$(eval $(call BuildPackage,meta-acmeconf))
